using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TenmoServer.Models
{
    public class Transfer
    {
        /// <summary>
        /// The ID of the user SENDING funds
        /// </summary>
        public int FromUserId { get; set; }

        /// <summary>
        /// The ID of the user RECEIVING funds
        /// </summary>
        public int ToUserId { get; set; }

        /// <summary>
        /// The amount in US Dollars to be transferred
        /// </summary>
        public decimal Amount { get; set; }
        /// <summary>
        /// 2001 approved
        /// </summary>
        public int TransferTypeId { get; set; }
        /// <summary>
        /// 1000 request
        /// </summary>
        public int TransferStatusId { get; set; }
        /// <summary>
        /// Autogenerated id
        /// </summary>
        public int TransferId { get; set; }
        public int AccountFrom { get; set; }
        public int AccountTo { get; set; }

        public string FromUserName { get; set; }

        public string ToUserName { get; set; }
        /// <summary>
        /// Request or Send
        /// </summary>
        public string TypeDescription { get; set; }
        /// <summary>
        /// Approved, Pending or Rejected
        /// </summary>
        public string StatusDescription { get; set; }
    }
}
