using System;
using System.Collections.Generic;
using System.Text;

namespace TenmoClient.Data
{
    /// <summary>
    /// Creates a transfer object
    /// </summary>
    public class Transfer
    {
        /// <summary>
        /// The ID of the user SENDING funds
        /// </summary>
        public int FromUserId { get; set; }

        /// <summary>
        /// The ID of the user RECEIVING funds
        /// </summary>
        public int ToUserId { get; set; }

        /// <summary>
        /// The amount in US Dollars to be transferred
        /// </summary>
        public decimal Amount { get; set; }

        /// <summary>
        /// 2001 approved
        /// </summary>
        public int TransferTypeId { get; set; } = 1001; //set default id to send
        /// <summary>
        /// 1000 request
        /// </summary>
        public int TransferStatusId { get; set; } = 2001; //set default id to approved
        /// <summary>
        /// Autogenerated id
        /// </summary>
        public int TransferId { get; set; } = -1; //set default value
        public int AccountFrom { get; set; }
        public int AccountTo { get; set; }

        public string FromUserName { get; set; }

        public string ToUserName { get; set; }
        /// <summary>
        /// Request or Send
        /// </summary>
        public string TypeDescription { get; set; } = "request";
        /// <summary>
        /// Approved, Pending or Rejected
        /// </summary>
        public string StatusDescription { get; set; } = "approved";
    }
}
